Avoid referencing keyrtn before assignment in aws_s3.py
Excerpt from traceback reported by Marc:

  File "/tmp/ansible_aws_s3_payload_8db1orzp/__main__.py", line 915, in <module>
  File "/tmp/ansible_aws_s3_payload_8db1orzp/__main__.py", line 813, in main
UnboundLocalError: local variable 'keyrtn' referenced before assignment

Obvious coding error. Rerunning would succeed because the bucket would
have been created on the last run, so the code would take a different
branch where keyrtn was assigned.

Signed-off-by: Abhijit Menon-Sen <ams@2ndQuadrant.com>